version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    volumes:
      - mongo_data:/data/db
    networks:
      - mean-net

  backend:
    image: ${DOCKERHUB_USERNAME}/mean-backend:latest
    restart: unless-stopped
    environment:
      PORT: 8080
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: mongo_user
      MONGO_PASS: mongo_pass
      MONGO_DB: tutorials_db
    depends_on:
      - mongo
    networks:
      - mean-net
    ports:
      - "8080:8080"

  frontend:
    image: ${DOCKERHUB_USERNAME}/mean-frontend:latest
    restart: unless-stopped
    networks:
      - mean-net
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  mean-net:

volumes:
  mongo_data:
